### ISSUE TITLE
Questions about implementation

### ISSUE THREAD

**Issue by duxiaodan** [thaoshibe/visii#2]
Hello,

I'm trying to implement your paper on my own. I'm confused with the "reusing identical noises during inference" part.

During training, since we are randomly sampling timestep t, there could be multiple or no noises sampled for a specific t. For example, with T=1000, during training I could have sampled t=200 twice and never sampled t=100. During inference time, what noises should I use for t=200 and t=100?

Which inference method do you use? If I use deterministic ODE solvers such as DDIM, where no noise is needed during backward process, what should I do?

Do you have an estimated time for code release?

Thank you!

**Comment by thaoshibe** [comment]
Hello,
I sample noises for every timesteps before training.
For example, if I train for T=1000 timesteps, then I'll generate a set of noises {e1, e2, ..., e1000}.
Save this sequence of noises somewhere, and I reuse it in the test time.

**Comment by duxiaodan** [comment]
Thank you for the reply. What scheduler do you use for inference?

**Comment by thaoshibe** [comment]
I used [EulerAncestralDiscreteScheduler](https://huggingface.co/docs/diffusers/api/schedulers/euler_ancestral). But I found as long as you use the same scheduler in training for inference, it should be good.
