### ISSUE TITLE
Is Visii likely to release its code anytime in the future?

### ISSUE THREAD

**Issue by RoyZhao926** [thaoshibe/visii#3]
I'm very much looking forward to your open source : ) When will you release the code?  I am following Visii and doing related research, could you send me a pre-release version for reference? My email is as follows: RoyZhao@stu.xidian.edu.cn

**Comment by thaoshibe** [comment]
Hey, I have just uploaded the code, tested on all figures I used in the main paper, seems to be good. Hopefully you can improve upon it :D Thank you!
