### ISSUE TITLE
Question about the reproduce.

### ISSUE THREAD

**Issue by jongmin4422** [thaoshibe/visii#4]
Hi I have a quesion about the reproduct.

I trained a model according this commend.
"python train.py --image_folder ./images --subfolder painting1"

And then, I test a model using this commend.
"python test.py --prompt 'a husky'"

However, the results I got are quite different from what the GitHub README suggests.
![image](https://github.com/thaoshibe/visii/assets/31647995/6e2357a2-e4a7-466d-86e3-045fbb6fec78)
![image](https://github.com/thaoshibe/visii/assets/31647995/7e1ba166-9a19-47bc-8295-65bbb128875e)

Which options can I change to achieve the same output?

Thank you!

**Comment by thaoshibe** [comment]
Hello, can you check optimization progress [guideline here](https://github.com/thaoshibe/visii#optimizing-progress), or [Tips](https://github.com/thaoshibe/visii#optimizing-progress) here?

But base on your results, it seems like the Optimization is not converged yet! I'd suggest run it once more and check the Optimization progress png file.
It should look like [this photo](https://github.com/thaoshibe/visii/blob/fc1fc48300dae50909a96dfca51223d42912e201/assets/images/optim_progress.png)
![](https://github.com/thaoshibe/visii/blob/fc1fc48300dae50909a96dfca51223d42912e201/assets/images/optim_progress.png)
Hope this helps!
