### ISSUE TITLE
Regarding the checkpoint issue

### ISSUE THREAD

**Issue by pipiofmark** [thaoshibe/visii#6]
Dear authors,

I hope this message finds you well. I'm currently attempting to replicate the Visual Instruction Inversion project you shared on GitHub. However, I couldn't locate any checkpoints related to InstructPix2Pix within the provided codebase.

While going through the 'train.py' file, I noticed that the default checkpoint should be placed in the './logs/' directory. Regrettably, I couldn't find this directory within the project.

I wanted to inquire whether this code includes the checkpoint section. If not, would it be possible for me to request a checkpoint from you to facilitate my replication process?

Thank you sincerely for your time and consideration. I eagerly await your response.

Best regards,
Zou Ling

**Comment by thaoshibe** [comment]
There is no pre-trained checkpoints.
Checkpoints (embeddings) will be saved in logs after you run python train.py.
Hope this helps!
