### ISSUE TITLE
Controlnet and Checkpoint

### ISSUE THREAD

**Issue by yuntaodu** [thaoshibe/visii#8]
Hi, thanks for your work. I have some questions as follows:

1) how to perform with controlnet using the following command, as there is no such file named train_controlnet.py
```
python train_controlnet.py --image_folder ./images --subfolder painting1
```

2) Could you release a checkpoint that is trained on the combination of the subset of CleanInstructPix2Pix and other data, such that we could reproduce the results of Figure 7, the main result of this paper?

**Comment by thaoshibe** [comment]
Hello yuntaodu,
1. Unfortunately, the [ControlNet's ](https://huggingface.co/lllyasviel/control_v11e_sd15_ip2p) is not stable (often yield goods results), so I didn't commit train.py for ControlNet.

2. For Figure 7, I randomly selected a subset of CleanInstructPix2Pix; (as quoted in the paper: "For all of the studies below, we sample 100 editing directions (resulting in 400 before-and-after pairs in total)"). To save disk storage, I didn't save the checkpoints for each pair either -- I simply trained the instruction; then apply it to test-images and get results.

Most of visual results are in the [Supplementary Material](https://openreview.net/forum?id=l9BsCh8ikK&referrer=%5Bthe%20profile%20of%20Yong%20Jae%20Lee%5D(%2Fprofile%3Fid%3D~Yong_Jae_Lee2)).

Sorry for late reply also, hope this helps!
